<<<<<<< HEAD
# Generated by Django 3.2.7 on 2021-09-27 09:29
=======
# Generated by Django 3.2.7 on 2021-09-27 09:27
>>>>>>> 5ad302c53ce317e6e7d1baff194ecfed7dec66af

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_alter_customuser_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
